chore(manifests): Add test to verify that no avro schema cache is used with manifest files (#402)
This is a follow-up to #385, which added a similar test for manifest
_lists_ (but not for manifest files).

I verified the efficacy of this new test by commenting out the calls to
`ocf.WithDecoderSchemaCache` in `readManifestEntries` and
`NewManifestWriter` (which were added in #385). When they are commented
out, the process uses avro's default global cache and the test then
fails (as expected) with the following:

```
=== RUN   TestManifests/TestReadManifestIncompleteSchema
    manifest_test.go:911: 
        	Error Trace:	/Users/jhumphries/src/iceberg-go/manifest_test.go:911
        	Error:      	An error is expected but got nil.
        	Test:       	TestManifests/TestReadManifestIncompleteSchema
--- FAIL: TestManifests/TestReadManifestIncompleteSchema (0.00s)
```